services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/acme.json
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - web
    labels:
      - "traefik.enable=true"

      # 1. Router for the Traefik Dashboard
      - "traefik.http.routers.dashboard.rule=Host(`traefik.fancydictionary.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt" # <-- Added this for SSL
      - "traefik.http.routers.dashboard.middlewares=auth"

      # 2. Middleware for Basic Authentication
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$2y$$10$$yourhashedpassword"


  dictionary-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        REACT_APP_DOMAIN: ${REACT_APP_DOMAIN}
        REACT_APP_EMAIL: ${REACT_APP_EMAIL}
        REACT_APP_TRAEFIK_PASSWORD_HASH: ${REACT_APP_TRAEFIK_PASSWORD_HASH}
        REACT_APP_PROJECT_DIR: ${REACT_APP_PROJECT_DIR}
        REACT_APP_ENV: ${REACT_APP_ENV}
        REACT_APP_SERVER_URL: ${REACT_APP_SERVER_URL}
        NODE_ENV: production
    container_name: dictionary-app
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dictionary.rule=Host(`fancydictionary.com`)"
      - "traefik.http.routers.dictionary.entrypoints=websecure"
      - "traefik.http.routers.dictionary.tls.certresolver=letsencrypt"
      - "traefik.http.services.dictionary.loadbalancer.server.port=80"
      - "traefik.docker.network=web"

networks:
  web:
    external: true 