name: Deploy to Production

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test -- --watchAll=false --passWithNoTests
    
    - name: Build app
      run: npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: Prod
    steps:
    - name: Deploy to production server
      uses: appleboy/ssh-action@v1.0.3
      env:
        DOMAIN: ${{ vars.DOMAIN }}
        EMAIL: ${{ vars.EMAIL }}
        TRAEFIK_PASSWORD_HASH: ${{ vars.TRAEFIK_PASSWORD_HASH }}
        PROJECT_DIR: ${{ vars.PROJECT_DIR }}
      with:
        host: ${{ vars.HOST }}
        username: ${{ vars.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ vars.PORT }}
        script: |
          cd ${{ vars.PROJECT_DIR }}
          ./scripts/deploy.sh 